

env: "uav_env"

env_args:
    map_name: "uav_env"
    grid_shape: [25,25] 
    n_agents: 2
    read_map: False
    observe_ids: False     
    observe_one_hot: False  
    obs_last_action: False
    observability: 0
test_greedy: True
test_nepisode: 30
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
save_model_interval: 500000
t_max: 2050000
save_model: True
obs_agent_id: False
